/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store_app;

import javax.swing.JOptionPane;



/**
 *
 * @author PC
 */
public class VentanaAlmacen extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAlamacen
     */
     Service s1 = new Service();
    
    public VentanaAlmacen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnMorochas = new javax.swing.JButton();
        btnTentacion = new javax.swing.JButton();
        btnRitz = new javax.swing.JButton();
        btnCasino = new javax.swing.JButton();
        btnClubsocial = new javax.swing.JButton();
        btnOreo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Harlow Solid Italic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Tienda de Galletas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 440, 60));

        btnMorochas.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        btnMorochas.setText("Morochas");
        btnMorochas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMorochasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMorochas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 180, 70));

        btnTentacion.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        btnTentacion.setText("Tentacion");
        btnTentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnTentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 180, 70));

        btnRitz.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        btnRitz.setText("Ritz");
        btnRitz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRitzActionPerformed(evt);
            }
        });
        getContentPane().add(btnRitz, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 70));

        btnCasino.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        btnCasino.setText("Casino");
        btnCasino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasinoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCasino, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 180, 70));

        btnClubsocial.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        btnClubsocial.setText("Club\nSocial");
        btnClubsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClubsocialActionPerformed(evt);
            }
        });
        getContentPane().add(btnClubsocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, 70));

        btnOreo.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        btnOreo.setText("Oreo");
        btnOreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOreoActionPerformed(evt);
            }
        });
        getContentPane().add(btnOreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 180, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store_app/IMAGES/fondoTienda.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMorochasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorochasActionPerformed

        JOptionPane.showMessageDialog(null,"Galleta Morochas: "+s1.morochas+" unidades.");
    }//GEN-LAST:event_btnMorochasActionPerformed

    private void btnRitzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRitzActionPerformed
       
        JOptionPane.showMessageDialog(null,"Galleta Ritz: "+s1.ritz+" unidades.");
    }//GEN-LAST:event_btnRitzActionPerformed

    private void btnClubsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClubsocialActionPerformed
        JOptionPane.showMessageDialog(null,"Galleta Club Social: "+s1.clubsocial+" unidades.");
    }//GEN-LAST:event_btnClubsocialActionPerformed

    private void btnTentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentacionActionPerformed
        JOptionPane.showMessageDialog(null,"Galleta Tentacion: "+s1.tentacion+" unidades.");
    }//GEN-LAST:event_btnTentacionActionPerformed

    private void btnCasinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasinoActionPerformed
         JOptionPane.showMessageDialog(null,"Galleta Casino: "+s1.casino+" unidades.");
    }//GEN-LAST:event_btnCasinoActionPerformed

    private void btnOreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOreoActionPerformed
        JOptionPane.showMessageDialog(null,"Galleta Oreo: "+s1.oreo+" unidades.");
    }//GEN-LAST:event_btnOreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAlmacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCasino;
    private javax.swing.JButton btnClubsocial;
    private javax.swing.JButton btnMorochas;
    private javax.swing.JButton btnOreo;
    private javax.swing.JButton btnRitz;
    private javax.swing.JButton btnTentacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
